### ISSUE TITLE
Pulsefilenames date format not consistent

### ISSUE THREAD

**Issue by achim1** [achim1/muonic#52] opened 2015-06-15 10:02 UTC
It seems that the month is written like "6" instead of "06" in the name of the pulsefile

**Comment by aschulzdesy** [comment] 2015-07-21 08:43
Example here
![bildschirmfoto vom 2015-07-21 10_41_54](https://cloud.githubusercontent.com/assets/4849214/8796464/44922026-2f95-11e5-8447-a6c088974980.png)

**Comment by hpbretz** [comment] 2015-07-21 10:09
which version of muonic is this?

**Comment by hpbretz** [comment] 2015-07-21 10:12
Whit the current commit (2.0.15), it should work properly.

**Comment by aschulzdesy** [comment] 2015-07-22 08:16
Hi, this is not working. See screeshot: 
![bildschirmfoto vom 2015-07-22 10_14_02](https://cloud.githubusercontent.com/assets/4849214/8821018/a792daec-305a-11e5-912c-0e4aecedb3b8.png)

**Comment by hpbretz** [comment] 2015-07-22 09:21
Managed to reproduce the issue. This happens when one starts muonic without the option '-p', and then activates the pulse analyzer widget. In that case, the starting time of the pulse file is also different from the other file because a different time function (time.gmtime()) is used. I'll change this to use the same defintion at all places.

**Comment by hpbretz** [comment] 2015-07-22 09:36
Fixed in commit https://github.com/achim1/muonic/commit/04c044f174572faddfb766a113607639ab6da9bb

**Comment by hpbretz** [comment] 2015-08-05 09:54
test again with newest version. If it is fixed in 2.0.21, we need a new package with 2.0.21, because it doesn't work in 2.0.20

**Comment by hpbretz** [comment] 2015-08-10 15:27
Works properly in 2.0.22

**Closed as completed by hpbretz** 2015-08-10 15:27 UTC
Labels: Usability, test wanted
